[abrosexual]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[ace]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[agender]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[aro]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[aroace]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[bear]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[bisexual]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[demiboy]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[demigirl]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[demiromantic]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[femboy]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[gay]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[genderfluid]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[genderqueer]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[intersex]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[lesbian]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[nonbinary]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[omnisexual]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[pansexual]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[polyamory]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[progress]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[transbian]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[transgender]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]

[unlabeled]
artists = [
    { name = "phluxjr", link = "https://phluxjr.net" },
]
